spring.application.name=swiggy-backend

# ===============================
# DATABASE
# ===============================

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/swiggy_clone}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect


# ===============================
# SERVER
# ===============================

server.port=${PORT:8080}


# ===============================
# SWAGGER
# ===============================

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.packages-to-scan=com.swiggy.swiggy_backend.controller
springdoc.paths-to-match=/api/**


# ===============================
# JWT
# ===============================

jwt.secret=${JWT_SECRET:SwiggyCloneSecretKeyForJWTAuthentication12345678901234567890}
jwt.expiration=${JWT_EXPIRATION:86400000}


# ===============================
# MAIL
# ===============================

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:}
spring.mail.password=${MAIL_PASSWORD:}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.enable=false

spring.mail.properties.mail.debug=false


# ===============================
# FILE UPLOAD
# ===============================

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB


# ===============================
# REDIS
# ===============================

spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}

logging.level.org.springframework.cache=INFO
logging.level.org.springframework.data.redis=INFO
logging.level.org.springframework.cache.interceptor=INFO
logging.level.org.springframework.data.redis.serializer=INFO
logging.level.org.springframework.data.redis.cache=INFO